project-flogo/flow

- descriptor.json
- instance/util.go
```
[x] Bugfix
[] Feature
```
**Fixes**: github.com/project-flogo/core/issues/22
> fix related to issue github.com/project-flogo/core/issues/22

- definition/definition.go
- definition/definition_ser.go
- instance/instances.go
- instance/taskinst.go
- instance/util.go
- model/context.go
- model/simple/iteratorbehavior.go
```
[x] Bugfix
[] Feature
```
**Fixes**: Was not resolving iterator value expression
Add a "SettingsMapper" to the task, this will allow iterator to resolve activity outputs and use expression for the value to iterate on
> fix for iterator value resolve

- .travis.yml
```
[] Bugfix
[] Feature
[*] Other... Please describe: Travis CI
```
**Fixes**: #
No Travis on the repo
**What is the new behavior?*I
Adding .travis.yal to enable Travis CI
> Enable travis for the repo

- definition/resolve.go
```
[] Bugfix
[*] Feature
```
**Fixes**: #  Corresponding PR https://github.com/project-flogo/core/pull/45
> Add loop resolver for array mapping in object mapper

- definition/definition_ser.go
```
[] Bugfix
[] Feature
[*] Other... Please describe: core PR related changes
```
project-flogo/core PR https://github.com/project-flogo/core/pull/49 changed API by requiring resolver for second parameters.
> pass resolver to mapper converter

- instance/taskevents.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
> Edit task event to reflect changes made in 'fix iterator value resolve'

- instance/instance.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Fixes return of default values from Flow Output
If the default value is set in Flow, it does not return in the flow output.
> Fix implicit return

- action.go
- definition/definition.go
- definition/definition_ser.go
- instance/instance.go
- instance/taskinst.go
- ondemand/action.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Initial Activity Schema validation
> Initial Activity Schema validation

- action.go
- definition/definition_ser.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
> fix activity ref in definition

- instance/util.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Faced nil issue  `Execution failed for Activity[Mapper] in Flow[f1] - assignment to entry in nil map`
> avoid nil before set flow instance attrs

- definition/definition.go
- go.mod
- go.sum
- instance/instances.go
```
[x] Bugfix
[x] Feature
```
**Fixes**: #
Bugfix:  Set default values for input on flows
Feature: Add support for activity cleanup
> add cleanup support; fix default inputs to flow

- definition/definition_ser.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
The Engine will miss the input type for the literal value, sometimes it takes an int as float64
Convert input value to desire value before new mapper/
> convert input type to it's own type

- instance/instances.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Missing flow input
Add missed flow input into instances
> Fix missing flow inputs

- definition/definition_ser.go
- go.mod
- go.sum
```
[] Bugfix
[] Feature
```
**Fixes**: #
> legacy fix for activites

- activity/subflow/activity.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Change error to warning when getting flow metadata
> Change error log to warn log for subflow activity

- definition/definition.go
- definition/definition_ser.go
- definition/resolve.go
- go.mod
- go.sum
- instance/taskinst.go
```
[] Bugfix
[x] Feature
[x] Refactoring (no functional changes, no api changes)
```
**Fixes**: #
With LegacyCtx, we can add support in the legacybridge to handle legacy activities that accessed output directly.
Cleaned up error so it attaches a single error object to the flow
> add legacy ctx; fix error object

- definition/definition.go
- definition/definition_ser.go
- instance/taskinst.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Cannot get output from legacy context
Add output to flow definition and get output from legacy context
> Handle legacy output by adding output to flow definition.

- definition/definition_ser.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
1. While linker Expr not set while difficult to know which one.
2. Error msg not clear while activity, not registered 
`activity '' not imported`
Fixed those 2
> return more details when error occurs

- instance/taskinst.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Cannot get schema in legacy context
implement HasSchemaIO interface for legacy context to support schemas
> implement HasSchemaIO interface for legacy context to support schemas

- README.md
- activity/subflow/go.mod
- activity/subflow/go.sum
- go.mod
```
[] Bugfix
[] Feature
[x] Refactoring (no functional changes, no api changes)
```
**Fixes**: #
> update go mod & readme for release

- instance/taskinst.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
No way to get settings fields from legacy context
Implement GetSetting method in legacyCtx
> Able to get setting from legacy context

- definition/resolve.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Not able to handle `$iteration[value].EventSource` this case
> Handle iterator resolver to resolve $iteration[value].xxxx

- definition/resolve.go
- instance/instances.go
- instance/taskinst.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Today we are not adding error data to error branch scope
Add error data to the error branch to make error details available in the error branch
> Error branch

- definition/definition.go
- definition/definition_ser.go
- model/simple/taskbehavior.go
```
[] Bugfix
[*] Feature
```
**Fixes**: https://github.com/TIBCOSoftware/flogo/issues/436
Today, we don't have an otherwise linker to follow when only no other branch follows.
> support otherwise branch

- definition/resolve.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Last PR getting accumulates output where we remove dot for the attribute name but fogot to update resolver.  fix it now
> Fix issue to get accumulated value

- instance/taskinst.go
…ming value
```
[*] Bugfix
[] Feature
```
**Fixes**: #
outputs should be copied to new map otherwise it will be overridden by coming output value
> outputs should be copy to new map

- action.go
- go.mod
- go.sum
- instance/instance.go
- instance/instances.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
> add tracing context

- instance/instances.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Set task ready status only once after all branches are evaluated
> Task ready status set at correct place

- action.go
- instance/flowevents.go
- instance/instance.go
- instance/instances.go
- instance/taskinst.go
- support/event/flowevents.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Tracing Flow and tasks using tracing APIs added in core
> Added trace logic for flow and task

- instance/instances.go
- instance/taskinst.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
When last task was successfully completed, subflow trace was not completed.
When last task is successfully completed, subflow trace is now marked as complete
> Subflow trace issue

- definition/definition.go
- definition/definition_ser.go
- definition/resolve.go
- instance/taskinst.go
- model/simple/dowhilebehavior.go
- model/simple/iteratorbehavior.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Currently, do while iterates indefinitely and immediately if the condition evaluates to true.
User has the option to delay each repetition by a specific interval or limit the number of iteration by using `$dowhile["index"]` as part of the do while condition. Here, `dowhile["index"]` tracks the iteration index for the do while behavior. 
-- Added a new "dowhile" resolver
-- Updated the scope while evaluating the expression.
-- Changed some Debug logs to INFO to provide the user more …
> Add delay and index to dowhile

- instance/instances.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Due to tracing change, error returned by the task was always set to nil.
Issue is fixed
> Task error handling not working due to tracing related change

- model/simple/dowhilebehavior.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Init index value to 0 before running first do-while loop
> init index to 0 for dowhile loop

- definition/definition_ser.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
comment out output mapper for now. we can reconsider custom output mapper in the future.
> comment out output mapper

- instance/taskinst.go
- model/simple/dowhilebehavior.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
We fixed 2 issue in this PR.
1. We should update do-while index after condition evaluation
2.  While accurate enabled, we should also apply output mapper because we need output field for do-while condition field.   such as condition field: `$activity[REST].statusCode == 200 && $iteration[index] < 5`
> Fix issue on dowhile and accumulate

- action.go
- instance/instances.go
- instance/taskinst.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Starting trace for only ready task
> Skip eval for skipped task

- model/simple/taskbehavior.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Finishing previous trace when retry attempt on error is made.
> Trace is not completed when retry attempt is made on error

- go.mod
- go.sum
- instance/instance.go
- instance/instance_chg.go
- instance/instance_ser.go
- instance/instances.go
- instance/linkinst.go
- instance/recorder.go
- instance/taskinst.go
```
[] Bugfix
[] Feature
[x] Code style update (formatting, local variables)
```
**Fixes**: #
> cleanup change tracker

- definition/resolve.go
- instance/taskinst.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Handle error resolver with no path
> fix error resolver

- activity/subflow/activity.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
invalid port on flowURI parse
> remove uri parse check

- activity/subflow/activity.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
remove unused import
> Sf uri fix

- definition/resolve.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Changes as per https://github.com/project-flogo/core/pull/159
> Change as per core PR

- action.go
- tester/request.go
```
[x] Bugfix
[] Feature
```
**Fixes**: Fixes issue access remote flow
> fix flow manager; fix flowURI setting

- instance/instance_chg.go
```
[x] Bugfix
[] Feature
```
**Fixes**: state tracking nil pointer
> fix state tracking

- model/simple/taskbehavior.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Expr otherwise branch has an issue, the exprLinkFollowed should be set when only there is expression linker to follow.
> set exprLinkFollowed to true only when there has follow linker

- instance/instance_chg.go
- instance/instances.go
- state/change/change.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
> fix flow tracking

- instance/instance.go
- instance/instance_chg.go
- instance/instances.go
- state/change/change.go
```
[x] Bugfix
[] Feature
```
**Fixes**: Attr changes are not tracked when recording state
> Fix attr change tracking 

- instance/instance_ser.go
```
[] Bugfix
[] Feature
[x] Other... Please describe:
```
Update flow serialization to use map[string]interface{} instead of []*data.Attribute
> fix instance serialization

- action.go
- instance/ind_instance.go
- instance/instance_chg.go
- tester/request.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
> Fix step recording; fix def lookup on restart

- definition/mapper.go
- instance/ind_instance.go
- instance/instance.go
- model/behavior.go
- model/simple/taskbehavior.go
```
[x] Bugfix
[] Feature
```
**Fixes**:  One error, flows were ending prematurely do to error link removal code on done.  Switch skip propagation code so model has control whether it uses it or not.
> Skip change

- instance/taskinst.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
UI expose error `data` field to the user,  top avoid field not found, set data to nil by default.
> add data as error default field with nil value

- model/simple/taskbehavior.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
We missed the label link type while task done. 
Add label back
> Add label link type

- model/simple/taskbehavior.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Fix flow ending prematurely due to skip propogation
> sort task entries so skip prop is done last

- model/simple/tasjbehavior_test.go
- model/simple/taskbehavior.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
The branching order has been changed
Maintain the order of original tasks
> Move skip to last but maintain the order of original

- model/simple/taskbehavior.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
Otherwise, keep previous behavior to running first.
> keep previous order that expr otherwise running first

- instance/ind_instance.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
The task ready status is already set in the Enter(). This additional call sends duplicate Task Started event to event collector.
Removed redundant call
> Redundant task ready status

- definition/definition_ser.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Having issue to handle legacy connection model
Let connector to handle legacy connection engine will skip convert it to the connection object
> handle legacy connection to avoid convert to connection

- definition/definition_ser.go
- support/manager.go
- support/resource.go
```
[] Bugfix
[] Feature
[*] Refactoring (no functional changes, no api changes)
```
**Fixes**: #112 
Assume in flogo.json we set incorrect field value. such as assign `asdasd` to a bool field.  Today the error message reporting as
```
Failed to create engine: error unmarshalling flow: create task [log_3] error: convert value [asdasd] to type [bool] error: strconv.ParseBool: parsing "asdasd": invalid syntax
```
After enhancement of the error message, we clearly show which activity and in which flow failed with the reason.
```
Failed to create engine: creating task [log_3] inflow …
```
> Enhance the error message

- action.go
- instance/ind_instance.go
- instance/instance_chg.go
- ondemand/action.go
- state/change/change.go
- state/status.go
- state/status_test.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #115 
- Today no input data captured into state recorder
- We also not capture the return activity data
1. Add input data for each success tasks
2. able to get return data as well
> Add input data for each task that been recorded into state server

- instance/instance_chg.go
- state/change/change.go
- state/status.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
1. Debugger state mode does not enable snapshot which should be enabled.
2. There is no link from and to from linker in state step, it much better/easy to understand if we add from and to
1. Enable snapshot save for debugger model
2. Add from and to for linker in state  step
> Add from and to for linker in state step

- definition/definition_ser.go
- model/simple/taskbehavior.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #119 
Please refer to issue #119 
> Fix #119 to make error message more clear

- definition/definition.go
- definition/definition_ser.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #122 
Error reported when using app property with delay field.
The Loop delay field should support app property.
> adding loop delay field to support app property

- definition/definition_ser.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
```
Failed to create engine: error creating task [log_3] in flow [Main]: activity '#log' not imported
```
```
Failed to create engine: error creating task [log_3] in flow [Main]: incompatible app engine, the app using the activity [#log] which is not installed
```
> improve error message while activity not import

- instance/ind_instance.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Today's error message when error happens at expression linker which not clearly show the flow name etc. 
```
Error starting action: error executing link [LogMessage -> LogMessage1]: failed to resolve flow attr: 'id2', not found in flow
```
New error
```
Error starting action: handle task [LogMessage] done in flow [asdasd] error: error executing link [LogMessage -> LogMessage1]: failed to resolve flow attr: 'id2', not found in flow
```
> add error details when error happens handle task done

- instance/instance_chg.go
- instance/linkinst.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
When saving step data
1. Same of flow changes does not have a task id 
2. Sometimes the link data been overridden by others because of id conflict.
Fixed both of them
> Add each task id in step data and keep link id same as spec

- instance/ind_instance.go
```
[] Bugfix
[] Feature
[*] Other... Please describe: Enhance log
```
**Fixes**: #
Sometimes when there is an error that happens in the main flow and there is no error handler, nothing prints in the log which sometimes difficult to know what happened. 
Print logs
> add log for handling error in error handle or no error handler

- model/simple/taskbehavior.go
```
[] Bugfix
[] Feature
[*] Other... Please describe: enhance existing features.
```
**Fixes**: #136 
Today the sequence of branches execution base on the links array in flogo.json we follow the LAST one Running at FIRST. But this is somehow difficult with big apps with many many branches.  
Also, it is not friendly for Web UI which has some random behaviors. 
With new behavior,  we have the rule to run branches base on link types. 
1.  Success branch/ Lable type
2. Expression otherwise branch/Expr otherwise link type
3. Expression branches/Expr link …
> The order of branches execution

- instance/taskinst.go
```
[] Bugfix
[] Feature
[*] Other... Please describe: Enhance feature
```
**Fixes**: #
Today it just has flowId as part of context logging. 
Adding activity name, flow name, and flowId as part of context logging
> Add flow name, activityname and flowid as part of context logging

- instance/ind_instance.go
- instance/taskinst.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
There is no task data when iterator on the log message activity.
We should keep updating the task to the tracker when iterator on an activity
> Update state data to tracker when iterator on an activity

- go.mod
- go.sum
- instance/instance_chg.go
- util/util.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #142 
> Fix #142 by breaking flow data and state data reference

- definition/definition.go
- model/simple/taskbehavior.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Add link label when the error happens at execution.  part fixed at #144
> print label name when executing branch expressions

- instance/taskinst.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
> Moved activity execution time log to Debug

- state/util.go
```
[] Bugfix
[x] Feature
```
**Fixes**: # Now struct will be rich to include fields starttime & endtime 
**What is the current behavior?** doesnt have these fields
**What is the new behavior?** new fields in struct being added
> adding fields startime & endtime in FlowInfo

- instance/ind_instance.go
- state/flowstatus.go
- support/env.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
**What is the current behavior?** currently we logging appName for column appId
**What is the new behavior?**Now we will log appName into appName column and appVersion into appVersion column
> AppId replacing with AppName and AppVersion

- instance/ind_instance.go
- state/util.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
> Added new field Execution time and supported UTC timezone for flow's state collection

- instance/instance_chg.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
> adding the missing flowname entries into step data for tasks

- action.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
Currently flow status is not notified to event listeners when restarted
when flow is restarted, active status is notified to event listeners
> Set flow status to active when restarted

- action.go
- instance/ind_instance.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
When flow is restarted, appropriate state is not set for the flow and activity
Now when flow is restarted, status is explicitly set
> Initial status on restart

- definition/resolve.go
- instance/ind_instance.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
The flow details like Name, Id and name and Id of parent flow are not available in the mapper. 
The Flow Name, Id, Parent Flow Name and Id will now be available in the mapper.
> Flow Context variables (Name, Id, ParentName, ParentId) in Data Mapper.

- action_test.go
- definition/definition_ser_test.go
- instance/ind_instance.go
- instance/taskinst.go
- ondemand/action.go
```
[] Bugfix
[X] Feature
```
**Fixes**: #
Implemented new APIs added in the core https://github.com/project-flogo/core/pull/265/files
> Tracing context enhancements

- action.go
- definition/definition_ser.go
- instance/ind_instance.go
- instance/taskinst.go
- instance/util.go
- support/interceptor.go
```
[] Bugfix
[X] Feature
```
**Fixes**: #
Introduced code for applying assertion interceptor. 
This will be used as part of unit testing feature. 
No assertions are executed.
Now assertions will be executed for activities and flow outputs.
> Assertions support for Activities and Flow Output

- action.go
- definition/definition.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Flow action changes related to https://github.com/project-flogo/core/pull/270
> Dynamic reconfiguration support for Flow resource

- activity/subflow/activity_test.go
- definition/definition.go
- definition/definition_ser.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
Changes corresponding to https://github.com/project-flogo/core/pull/274
> Activity name in context

- instance/instance.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Now setting the output of actreply (Reply to Trigger) to the return data so that it will be visible in the flow output. This will help run the assertions on flow ouptut 
Output of actreply (Reply to Trigger)  is not available on flow output.
Output of actreply (Reply to Trigger)  is now available on flow output. This will help in executing the assertions.
> Updated fix for unit tesing for actreply output as part of flow outputs

- instance/taskinst.go
- instance/util.go
- support/interceptor.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Add missing fields for expressions in Unit test results
Currently the fields are missing in Unit test results
The new fields are added in the Unit test results
> Unit testing phase2

- instance/taskinst.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Set the error correctly
The error is set to global error by default
Now set global error only when the type is global error
> Updated fix for error handling

- action.go
- instance/ind_instance.go
- instance/linkinst.go
- support/interceptor.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
The activity input and output is not collected as part of test-case execution
The activity input and output will be also collected when running the test-case
> Unit testing phase3

- instance/ind_instance.go
- instance/taskinst.go
- model/simple/taskbehavior.go
```
[] Bugfix
[X] Feature
```
**Fixes**: #
Currently, retry on error is not supported for Subflow activity
With this change, now users can retry subflow execution based on error
> Supporting retry on error feature for subflow activity

- instance/ind_instance.go
- instance/instance.go
- instance/util.go
- support/interceptor.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
The i/o data for subflow was not available. 
The activity data for unit test subflow is also now tracked.
Optimization changes are also added.
> Unit test subflow

- action.go
- instance/ind_instance.go
- instance/instance.go
- instance/instance_chg.go
- instance/taskinst.go
- instance/util.go
- ondemand/action.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Currently flow is executed in sequential mode. So, overall flow execution time is equal to execution time of all activities in the flow. In certain case, activities can run in parallel. 
With this change, independent activities now run on separate gorotuines. This improves overall flow execution time.
> Concurrent flow execution

- model/simple/taskbehavior.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
Fixed the code revert issue
Flow terminates and doesnt go to next activity when no activity in branch is used.
Fixed the case.
> Fixed branch terminate issue when there is no activity
