- definition/definition_ser.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
The literal value in subflow activity input which got lost.
Because of subflow metadata comes from io metadata which cannot know when init flow.
> having issue with literal value as subflow input

- instance/flowevents.go
- instance/taskevents.go
- support/event/flowevents.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Today, there is no way to get activity ref as well as name of sub-flow activity that is invoking flow.
Added these two details in flow and task events so that collectors can use them in their implementation.
e.g. In oder to create sub-flow as a child span in open tracing,  we need to know span of sub-flow activity from parent flow. Also, we need to know when this relationship to be established. Using activity name and ref, we can easily achieve it.
> Added additional data in flow and task event

- instance/flowevents.go
- support/event/flowevents.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
The tracing context is set in the flow instance but not propagated to event listeners. Hence, event listeners not able to correlate spans.
Now, event listeners can access tracing context from the flow event for correlation.
> Propagating Tracing context set by trigger to Flow Event

- instance/instances.go
- instance/taskevents.go
- instance/taskinst.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Today, when task is running loop (e.g. iterator), there is no way to identify unique task instance.
Added counter that increments on every new execution of same task and exposed that over TaskEvent.
> Set unique task instance id and exposed it through TaskEvent

- model/simple/retry.go
- model/simple/taskbehavior.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
When an activity is not configured with retry, `getRetryData()` returned `error getting retry data`.
Error gets repeated at evalActivity()
1. Activity that throws a `RetriableError` but is not configured with retryOnError will not throw `error getting retry data` and activity is not retried on error.
2. Unnecessary duplication of error printing is removed from evalActivity()
> Fix retry data

- instance/instances.go
- model/simple/dowhilebehavior.go
- model/simple/iteratorbehavior.go
- model/simple/retry.go
- model/simple/taskbehavior.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
During the taskInstance creation, the task `Enter()` is called before the task's scheduleEval(). The Enter() method was setting the `SetTaskStatus()` to `Ready` which triggers the `postTaskEvent`. So the notification of `TaskStarted` does not have the `taskInstanceId` because the `taskInstanceId` was being assigned at `scheduleEval()`. 
TaskInstanceId = TaskId (done before task `Enter()` is called)
TaskInstanceId = TaskId - 'counter' (for repeating tasks). Done when `execTask` …
> fix for unique task-id

- definition/definition.go
- definition/definition_ser.go
- model/simple/taskbehavior.go
```
[] Bugfix
[] Feature
[*] Other... Please describe:
```
Today we do have the default, label, expression and error link types, The otherwise makes more confusing for the user to understand. 
The current behavior is: Execute otherwise branch when only there is no other link be executed. 
After discussing with @fm-tibco @vijaynalawade we agreed to change it to exprOtherwise,  it is only for expression type.  Just like the condition with condition false
**Fixes**: #
> Change otherwise link type to exprOtherwise

- definition/definition.go
- definition/definition_ser.go
- instance/taskinst.go
- model/simple/dowhilebehavior.go
- model/simple/iteratorbehavior.go
- model/simple/retry.go
```
[] Bugfix
[*] Feature
```
**Fixes**: #83 #82 
Previous we put dowhile under settings with dowhile node. 
```
"settings": {
"doWhile": {
"condition": "=$iteration[index] < 5",
"delay": 5
},
"accumulate": true
},
```
Now put it under settings to keep same with iterator 
```
"settings": {
"condition": "=$iteration[index] < 5",
"delay": 5,
"accumulate": true
}
```
Meanwhile we add `delay` field for iterator as well
> Consistence of dowhile and iterate in settings 

- activity/subflow/go.sum
- instance/ind_instance.go
- model/behavior.go
- model/simple/taskbehavior.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #88 
Please check ticker #88 for mode details, 
1. Flow get to hang when subflow end with an error branch
2. Running into infinite loop for some case that issue 1 invoked.
By remove/ignore the error branch in each task behavior `done` step. because the error already handled in eval for error branch meanwhile just return if the task status is skipped. 
Actually the fixes fixed both issues. but to make it more efficient I make optimization on skipped tasks by just update link and task …
> To fix hang issue and infinite loop issue

- instance/ind_instance.go
- model/simple/taskbehavior.go
```
[x] Bugfix
[] Feature
```
**Fixes**: #
when subflow instance is failed, setting subflow activity status to failed.
> Failed status is not set for Subflow task when subflow returns error

- go.mod
- go.sum
- support/definition.go
```
[] Bugfix
[] Feature
```
**Fixes**: #
Not able to set resources into existing resource manager which we want to support call subflow in flow tester
We use the default resource manager to manage all flows come from flow debugger to handle subflow etc... In that case we need a way to set the resource to the resource manager.
> Able to set resource in exist resource manager

- instance/ind_instance.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Today there is no error data append to task when activity error happens in the error handler flow which causing no data been save in state server. 
Add error data to task when the error happens in error handler flow.
> Append error data to task inst let it record in state server

- definition/definition.go
- instance/taskinst.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
For tester today we cannot run tile from the error handler.
Fixed the issue to make sure the tester able to run from tile from the error handler flow
> make sure able to run from tile from error handler

- instance/util.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Given below input for rest invoke and try to run from this tile and panic happens
```
{
"pathParams": null,
"queryParams": null,
"headers": null,
"content": null
}
```
It shouldn't panic as it is valid json
> NPE happens when run from tile has input field which has empty value

- activity/subflow/activity.go
- model/simple/retry.go
```
[*] Bugfix
[] Feature
```
**Fixes**: #
1. By default the log level of retrying on error is debug, we should change it to INFO to show it to the user by default to know that the activity now under retrying on error.
2. We print lots of warning messages if one app has many subflows which does nothing impact and we should remove it.
There are 2 fixes in this PR
1. Change Log level to Info for retrying on error
2. Remove warn log for call subflow activity
> change retry log level to info and remove warn log for subflow activity

- definition/definition.go
- definition/definition_ser.go
```
[] Bugfix
[*] Feature
```
**Fixes**: #144 
no label info in error message
Old error message:
```
error creating link[LogMessage -> Log2222] in flow [asdasd]: expression value not set on link[LogMessage -> Log2222]
```
New error Message:
```
error creating link [LogMessage -> Log2222] with label [Logg222LabelTesting] in flow [asdasd]: expression value not set on link
```
> Print branch label in error message

- definition/definition.go
- definition/definition_ser.go
- model/simple/dowhilebehavior.go
- model/simple/retry.go
```
[] Bugfix
[*] Feature
```
**Fixes**: #
Today the retry on error field count and interval just supports App property.  It would be super helpful to support mapping
Now user able to give mapping ref to count and interval. such as `"count":"$flow.body.count"`
> support mapper for retry on error

- model/simple/taskbehavior.go
- support/env.go
```
[] Bugfix
[] Feature
[x] Refactoring (no functional changes, no api changes)
```
**Fixes**: #
Make propagateSkip variable for taskbehavior configurable via env
With current code, we cannot configure it via env
The propagateSkip is now configurable via env var `FLOGO_TASK_PROPAGATE_SKIP`
> make propagate skip property configurable via env

- model/simple/taskbehavior.go
- support/env.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Currently the order of execution for link types is this:
1. Label or success branch
2. Otherwise branch
3. Expression branches
4. Default or dependency link type
When we set the env flag `FLOGO_TASK_PRIORITIZE_EXPR_LINK` to `true` the order will change to:
1. Expression branches
2. Otherwise branch
3. Label or success branch
4. Default or dependence link type
The default value for this flag is set to `false`. This will ensure the old behavior is unchanged.
> add env flag to change task link priority

- definition/definition.go
- definition/definition_ser.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Currently activity host name is not available in the InitContext or activityConfig. Due to this, activity host name can not be used during initialization. e.g. Pulsar producer name
With this change, contribution developers can access activity host name during initialization.
> add hostname in the activityConfig, initCtxImpl

- action.go
- activity/subflow/activity.go
- activity/subflow/descriptor.json
- instance/exec.go
- instance/util.go
```
[] Bugfix
[x] Feature
```
**Fixes**: #
Currently subflow invocation is inlined with main flow. So, main flow waits for subflow to complete. In fire and forget use cases, users would like to simply invoke subflows asynchronously without subflow completion. This is not possible today.
With this change, users can enable fire and forget use cases
> Supporting detached mode for subflow invocation
